name: Post Review Build URL to PR
on:
  pull_request:
    types: [opened]
jobs:
  example:
    name: Post to PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-branch-name-sanitized
        name: Sanitize branch name
        shell: bash
        run: echo "::set-output name=branch::$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH" | tr -cd '[a-zA-Z0-9]-' | cut -b 1-40)"
      - name: Post Review Build URL
        if: startsWith(steps.get-branch-name-sanitized.outputs.branch, 'feature')
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Branch name is correct"
          check_for_duplicate_msg: true
# Comment by Juan-Moctezuma to test if I have permission on this repository
